[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.7.6"
evm_version = "istanbul"
optimizer = true
optimizer_runs = 800
remappings = [
    "forge-std/=lib/forge-std/src/",
    "v3-core/=lib/v3-core/contracts/",
]
fs_permissions = [{ access = "write", path = "../engine/fixtures" }]
